#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/redirect_me {\n\t\treturn 301 http://www.holbertonschool.com permanent;" /etc/nginx/sites-available/default
sudo systemctl restart nginx
