#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line
n=1
while ((n < 10))
do
    echo "Holberton School"
    if ((n == 9-1))
    then
        echo "Hi"
    fi
    ((n++))
done
