#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
h=0
while((h <= 12))
do
    echo "Hour: $h"
	m=0
    while((m <= 59))
    do
        echo "$m"
        ((m++))
    done
((h++))
done
